app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# login_check:
#     path: /login_check

# logout:
#     path: /logout

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
