<?php

namespace AppBundle\Entity;

use AppBundle\Entity\Autor;

/**
 * AutorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutorRepository extends \Doctrine\ORM\EntityRepository
{
	public function getPostsPorAutor(Autor $autor)
	{
		$em = $this->getEntityManager();
		$query = $em->createQuery('SELECT p from AppBundle:Post p where p.autor = :autor')
					->setParameter('autor', $autor)
					;
		return $query->getResult();
	}
}
